<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pemasangan</name>
   <tag></tag>
   <elementGuidId>6cb74019-223e-42e8-9a09-52082a4976c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fbbc249-e79d-4f44-b589-6b95bf0f2481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4b66568f-2b18-4350-8d51-40816c6a960e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>2cdb36ca-178a-47e9-81e7-bc4fb9b85a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>-0.5</value>
      <webElementGuid>1d64e4c7-0b1c-44ce-9065-3b088430641f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-w647qe-0 iPPeqj</value>
      <webElementGuid>3615c33d-cb55-4b69-8303-4172fed6c89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pemasangan</value>
      <webElementGuid>a7b8a02c-4655-4dba-adcb-3f5b6c079fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-7pk9t0-0 InUea&quot;]/section[@class=&quot;sc-7pk9t0-2 ruYLe&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-1adxfw0-0 hQSVgD&quot;]/div[@class=&quot;sc-1adxfw0-3 bDMcRL&quot;]/div[@class=&quot;sc-1crxk01-0 hBGxiZ sc-1bwe4v7-0 cUSUGw&quot;]/span[@class=&quot;sc-w647qe-0 iPPeqj&quot;]</value>
      <webElementGuid>dbf97f83-ef4a-4d2c-97a2-865ea21d3d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/div/div[2]/div/span</value>
      <webElementGuid>2e0c497a-6706-4209-b4e0-fb891d32b1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spareparts'])[1]/following::span[2]</value>
      <webElementGuid>ee3a6da9-898b-4dda-9b0b-74d25a0e158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homeservice'])[1]/preceding::span[2]</value>
      <webElementGuid>9ee7ab9a-18a7-4867-99f5-96058b46cfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksesoris'])[1]/preceding::span[4]</value>
      <webElementGuid>9d8e3273-25a9-4b25-bdfb-c25df6375eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pemasangan']/parent::*</value>
      <webElementGuid>f2941379-ac89-4920-ac54-373ff446e325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>23817bcb-51f0-4cec-a427-63489cbf9d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pemasangan' or . = 'Pemasangan')]</value>
      <webElementGuid>397942f7-f3fc-4210-ac69-ae1e6374e919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
