<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mesin</name>
   <tag></tag>
   <elementGuidId>4d1541e7-9389-44fd-843b-4d074ff96cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-1crxk01-0.lkwwJy.sc-1adxfw0-2.ftoGfc > div.sc-1crxk01-0.hBGxiZ > div.sc-1crxk01-0.DxRlE > span.sc-w647qe-0.iPPeqj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/div/div[4]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8d73c52-eb9b-41ea-9361-6938667ff09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8a742491-3d6b-4b33-b9e5-5abedd13c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>ccd6396d-8927-4ee6-8d25-438731d551bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>-0.5</value>
      <webElementGuid>d0b29718-add2-4077-8428-7cf288c76dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-w647qe-0 iPPeqj</value>
      <webElementGuid>d3863e8a-986c-42d3-bbe3-b2e58528abef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mesin</value>
      <webElementGuid>b5b4e794-8e25-456d-8b8c-b5031c6fd486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-7pk9t0-0 InUea&quot;]/section[@class=&quot;sc-7pk9t0-2 ruYLe&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-1adxfw0-0 hQSVgD&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-1adxfw0-2 ftoGfc&quot;]/div[@class=&quot;sc-1crxk01-0 hBGxiZ&quot;]/div[@class=&quot;sc-1crxk01-0 DxRlE&quot;]/span[@class=&quot;sc-w647qe-0 iPPeqj&quot;]</value>
      <webElementGuid>1286aa73-68bb-48cc-ba99-9e4dfce17932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/div/div[4]/div/div/span[2]</value>
      <webElementGuid>7fc3e735-79d7-40a8-b190-fd5b8de748cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil'])[1]/following::span[2]</value>
      <webElementGuid>3b58098d-a169-4823-a552-9770ac3bf027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemasangan'])[1]/following::span[5]</value>
      <webElementGuid>be0277e8-80c0-48b1-853e-c0f6b67d12cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaki-kaki'])[1]/preceding::span[2]</value>
      <webElementGuid>0ceaa283-3c86-42e9-a82a-39a74af9014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Battery'])[1]/preceding::span[4]</value>
      <webElementGuid>57b462f3-70aa-47aa-99ac-a559041499e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mesin']/parent::*</value>
      <webElementGuid>6191bfb9-c260-4e46-a804-f04bec1def11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span[2]</value>
      <webElementGuid>b5830fd0-eac8-46e4-8ef0-daf7db5ab2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mesin' or . = 'Mesin')]</value>
      <webElementGuid>1960a81f-aa58-4d8b-a698-89d6c9d0e5be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
